name: Deploy Property Manager Admin Dashboard

on:
  push:
    branches:
    - main
    paths:
    - 'frontend/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
          role-session-name: github-property-manager-frontend-build
          aws-region: eu-west-1

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm i
        working-directory: frontend

      - name: Build
        run: npm run build
        working-directory: frontend

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
          role-session-name: github-property-manager-frontend-deploy
          aws-region: eu-west-1

      - name: Deploy to S3 Bucket
        run: aws s3 cp --recursive build s3://${{ secrets.FRONTEND_S3_DEPLOY_BUCKET }}
